### PR TITLE
Add CouplingElement

### PR DESCRIPTION
**Pull request by jguarato**
I started to develop a generic class for coupling elements [[Ref]](https://www.scielo.br/j/jbsmse/a/cbGYJZtfd6kRJPF49Q3fV4G/?format=pdf&lang=en). As input parameters, I considered mass, moments of inertia, translational and rotational stiffnesses for all directions, as well as damping.
Two models were adopted: `CouplingElement` (4 DoF model) and `CouplingElement6DoF`.

However, some doubts arose regarding how to implement this class. Would it be better to define it as a subclass of ShaftElement?

These first commits are just the initial ideas I had, which can be adjusted as needed.

### CODE REVIEW

**Comment by Pierre-zhu** [comment]
that's good idea, aslo that's all good news

**Review by raphaeltimbo — APPROVED** [review]

**Comment by Pierre-zhu** [comment]
could we try to use coupling element for calculation now?

**Comment by jguarato** [comment]
> could we try to use coupling element for calculation now?

Yes, you can try it now. If you encounter any problems, please report them in [_Issues_](https://github.com/petrobras/ross/issues).

**Comment by Pierre-zhu** [comment]
when I know bending stiffness , torisional stiffness ,axial stifness, radial stiffness , how to I　define couplingElement ，and how to add into shafElement?

**Comment by jguarato** [comment]
> when I know bending stiffness , torisional stiffness ,axial stifness, radial stiffness , how to I　define couplingElement ，and how to add into shafElement?

I've already answered you in the [discussions](https://github.com/petrobras/ross/discussions/1134). Let me know, if you have any questions.

**Pull request merged**
